### ISSUE TITLE
Defining boundary edges in the code

### ISSUE THREAD

**Issue by amanjain1397** [ranahanocka/MeshCNN#17]
![has_boundaries](https://user-images.githubusercontent.com/24360215/62695749-8e2d4100-b9f4-11e9-8262-5a2b9cf2e48d.PNG)

Hi Rana,

If I am not wrong, the function **has_boundaries** determines whether an edge is a boundary edge or not. So why are we checking the connectivity of the adjacent edges of a given edge (having edge_id = edge_id)?

**Comment by ranahanocka** [comment]
Hi @amanjain1397 ,

we used has_boundaries to check if any edges "nearby" are boundaries. We didn't want to collapse edges which have boundaries in their 1-ring, since these cases are complicated and can cause non-manifold geometries to occur. For example, this edge is not a boundary edge:
![image](https://user-images.githubusercontent.com/14359648/62715487-46fd7b00-ba09-11e9-926e-a05a36ade79c.png)
but there are boundaries in it's 1-ring. And collapsing it results in a non-manifold vertex.

**Comment by amanjain1397** [comment]
Thanks for the clarification, Rana.
