### ISSUE TITLE
Segmentation network configuration

### ISSUE THREAD

**Issue by eduardo-vp** [ranahanocka/MeshCNN#99]
Hi, I was reading the code and tried to find this part of the paper in the code but I couldn't.

![ss](https://user-images.githubusercontent.com/32459232/93944212-d3e0c200-fcf9-11ea-996b-ba4be0b5c25d.png)

I guess that it was changed in the code but I'm not completely sure about it.

**Comment by Eisorak** [comment]
Hi @eduardovp97 

I'm stuck on this figure, can you explain me what you understood about the steps used please?
or provide me with a shema to understand.

thank you

**Comment by eduardovp97** [comment]
If I'm not mistaken, the lines with ResConv are the ones related to the channels per edge (input channels x output channels)  and the lines with MeshPool describe a pooling operation that will be done until the mesh has the specified number of edges.

**Comment by Eisorak** [comment]
thank you for your answer.
I think what you are looking for is in the options/base_options.py file in #network params.

**Comment by eduardovp97** [comment]
Actually, I think that info is in scripts/coseg_seg/train.sh or scripts/human_seg/train.sh. However, the numbers don't match with the ones in the image and my guess is that they were changed but I'm not sure.

**Comment by ranahanocka** [comment]
Hi,

In general the code is more reliable than this table (and there is a typo in the table). 

The convolutions listed in the Table look correct since: 
https://github.com/ranahanocka/MeshCNN/blob/15b83cc6a4db968baf6cf595df78995a9c2dcee3/scripts/human_seg/train.sh#L9

So the first convolutional layer goes from # of input features (which is 5), and then to 32. And then second layer goes from 32 to 64, and so on. These are residual conv blocks with skip connections.

The pooling is a typo (I think it was copied from the another table in the paper which used MeshCNN for classification). Anyway, what is in the code is correct:
https://github.com/ranahanocka/MeshCNN/blob/15b83cc6a4db968baf6cf595df78995a9c2dcee3/scripts/human_seg/train.sh#L11
